// Utility to generate high-quality 3D geometries and pack them as Binary STL files
// The binary STL format consists of:
// - 80-byte header
// - 4-byte little-endian uint32 (number of triangles)
// - For each triangle:
//   - Normal vector: 3x 32-bit floats (12 bytes)
//   - Vertex 1: 3x 32-bit floats (12 bytes)
//   - Vertex 2: 3x 32-bit floats (12 bytes)
//   - Vertex 3: 3x 32-bit floats (12 bytes)
//   - Attribute byte count: 2 bytes (usually 0)
// Total size = 80 + 4 + (n * 50) bytes

interface Vertex {
  x: number;
  y: number;
  z: number;
}

interface Triangle {
  normal: [number, number, number];
  v1: [number, number, number];
  v2: [number, number, number];
  v3: [number, number, number];
}

// Simple cross product helper to calculate outward normals
function calculateNormal(v1: [number, number, number], v2: [number, number, number], v3: [number, number, number]): [number, number, number] {
  const ux = v2[0] - v1[0];
  const uy = v2[1] - v1[1];
  const uz = v2[2] - v1[2];
  
  const vx = v3[0] - v1[0];
  const vy = v3[1] - v1[1];
  const vz = v3[2] - v1[2];
  
  const nx = uy * vz - uz * vy;
  const ny = uz * vx - ux * vz;
  const nz = ux * vy - uy * vx;
  
  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len === 0) return [0, 0, 1];
  return [nx / len, ny / len, nz / len];
}

// Core function to convert an array of triangles into a binary STL ArrayBuffer
export function serializeBinarySTL(triangles: Triangle[], filename: string = "Procedural"): ArrayBuffer {
  const headerText = `STL generated by STL 3D Viewer - ${filename.substring(0, 40)}`;
  const buffer = new ArrayBuffer(84 + triangles.length * 50);
  const view = new DataView(buffer);
  
  // Write header (80 bytes)
  for (let i = 0; i < 80; i++) {
    if (i < headerText.length) {
      view.setUint8(i, headerText.charCodeAt(i));
    } else {
      view.setUint8(i, 32); // Space character
    }
  }
  
  // Write triangle count (4 bytes, little endian)
  view.setUint32(80, triangles.length, true);
  
  let offset = 84;
  for (const t of triangles) {
    // Write Normal (3x floats)
    view.setFloat32(offset + 0, t.normal[0], true);
    view.setFloat32(offset + 4, t.normal[1], true);
    view.setFloat32(offset + 8, t.normal[2], true);
    
    // Write V1 (3x floats)
    view.setFloat32(offset + 12, t.v1[0], true);
    view.setFloat32(offset + 16, t.v1[1], true);
    view.setFloat32(offset + 20, t.v1[2], true);
    
    // Write V2 (3x floats)
    view.setFloat32(offset + 24, t.v2[0], true);
    view.setFloat32(offset + 28, t.v2[1], true);
    view.setFloat32(offset + 32, t.v2[2], true);
    
    // Write V3 (3x floats)
    view.setFloat32(offset + 36, t.v3[0], true);
    view.setFloat32(offset + 40, t.v3[1], true);
    view.setFloat32(offset + 44, t.v3[2], true);
    
    // Attribute byte count (2 bytes)
    view.setUint16(offset + 48, 0, true);
    
    offset += 50;
  }
  
  return buffer;
}

// 1. CALIBRATION CUBE (Cubo de Calibración de 20x20x20 mm)
export function generateCalibrationCube(): ArrayBuffer {
  const size = 20; // 20mm
  const half = size / 2;
  
  const vertices: Vertex[] = [
    { x: -half, y: -half, z: -half }, // 0
    { x:  half, y: -half, z: -half }, // 1
    { x:  half, y:  half, z: -half }, // 2
    { x: -half, y:  half, z: -half }, // 3
    { x: -half, y: -half, z:  half }, // 4
    { x:  half, y: -half, z:  half }, // 5
    { x:  half, y:  half, z:  half }, // 6
    { x: -half, y:  half, z:  half }, // 7
  ];
  
  // Define faces: each face has 2 triangles. Normals point outwards.
  const facesDef = [
    // Bottom (-Z)
    [2, 1, 0], [3, 2, 0],
    // Top (+Z)
    [4, 5, 6], [4, 6, 7],
    // Front (-Y)
    [0, 1, 5], [0, 5, 4],
    // Back (+Y)
    [2, 3, 7], [2, 7, 6],
    // Left (-X)
    [3, 0, 4], [3, 4, 7],
    // Right (+X)
    [1, 2, 6], [1, 6, 5]
  ];
  
  const triangles: Triangle[] = [];
  for (const f of facesDef) {
    const v1 = vertices[f[0]];
    const v2 = vertices[f[1]];
    const v3 = vertices[f[2]];
    
    const p1: [number, number, number] = [v1.x, v1.y, v1.z];
    const p2: [number, number, number] = [v2.x, v2.y, v2.z];
    const p3: [number, number, number] = [v3.x, v3.y, v3.z];
    const normal = calculateNormal(p1, p2, p3);
    
    triangles.push({ normal, v1: p1, v2: p2, v3: p3 });
  }
  
  return serializeBinarySTL(triangles, "CalibrationCube_20mm");
}

// 2. FACETED DIAMOND (Gema Brillante de 25mm)
export function generateFacetedDiamond(): ArrayBuffer {
  const rTop = 12.0;       // top radius ring
  const rGirdle = 15.0;    // girdle (widest point)
  const hTop = 5.0;        // height girdle to table (top)
  const hPaved = 15.0;     // height girdle to bottom culet
  
  // We can build top center table (0, 0, hTop)
  // Crown rings: top ring (8 vertices), girdle ring (8 vertices), bottom culet (0, 0, -hPaved)
  const segments = 8;
  const vertices: Vertex[] = [];
  
  const tableZ = hTop;
  const girdleZ = 0;
  const culetZ = -hPaved;
  
  // Table center (Vertex 0)
  vertices.push({ x: 0, y: 0, z: tableZ });
  
  // Upper ring (8 points) (Vertices 1..8)
  for (let i = 0; i < segments; i++) {
    const ang = (i / segments) * Math.PI * 2;
    vertices.push({
      x: Math.cos(ang) * rTop,
      y: Math.sin(ang) * rTop,
      z: tableZ
    });
  }
  
  // Girdle ring (8 points) (Vertices 9..16)
  for (let i = 0; i < segments; i++) {
    const ang = ((i + 0.5) / segments) * Math.PI * 2; // offset to break alignment and create facets
    vertices.push({
      x: Math.cos(ang) * rGirdle,
      y: Math.sin(ang) * rGirdle,
      z: girdleZ
    });
  }
  
  // Culet (bottom point) (Vertex 17)
  vertices.push({ x: 0, y: 0, z: culetZ });
  
  const triangles: Triangle[] = [];
  
  // Crown Top Table (Polygon fans around vertex 0)
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const v1 = 0;
    const v2 = 1 + i;
    const v3 = 1 + next;
    
    const p1: [number, number, number] = [vertices[v1].x, vertices[v1].y, vertices[v1].z];
    const p2: [number, number, number] = [vertices[v3].x, vertices[v3].y, vertices[v3].z]; // Swapped for normal
    const p3: [number, number, number] = [vertices[v2].x, vertices[v2].y, vertices[v2].z];
    
    triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
  }
  
  // Crown Upper Triangles (Table ring to Girdle)
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const u1 = 1 + i;
    const u2 = 1 + next;
    const g1 = 9 + i;
    const g2 = 9 + ((i - 1 + segments) % segments);
    
    // Triangle pointing up (u1, u2, g1)
    {
      const p1: [number, number, number] = [vertices[u1].x, vertices[u1].y, vertices[u1].z];
      const p2: [number, number, number] = [vertices[u2].x, vertices[u2].y, vertices[u2].z];
      const p3: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
      triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
    }
    
    // Triangle pointing down (u1, g1, g2)
    {
      const p1: [number, number, number] = [vertices[u1].x, vertices[u1].y, vertices[u1].z];
      const p2: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
      const p3: [number, number, number] = [vertices[g2].x, vertices[g2].y, vertices[g2].z];
      triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
    }
  }
  
  // Pavilion (Girdle to Culet)
  const culetIdx = 17;
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const g1 = 9 + i;
    const g2 = 9 + next;
    
    const p1: [number, number, number] = [vertices[g2].x, vertices[g2].y, vertices[g2].z]; // Swapped for outward normals
    const p2: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
    const p3: [number, number, number] = [vertices[culetIdx].x, vertices[culetIdx].y, vertices[culetIdx].z];
    
    triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
  }
  
  return serializeBinarySTL(triangles, "FacetedDiamond_25mm");
}

// 3. MATHEMATICAL TORUS KNOT (Nudo Toroidal 3D - Sculptural)
// Spun from p=2, q=3 torus knot topology
export function generateTorusKnot(): ArrayBuffer {
  const pParam = 2;
  const qParam = 3;
  const majorRadius = 15;
  const minorRadius = 4;
  const tubeSegments = 64;
  const radialSegments = 12;
  
  const knotPoints: Vertex[] = [];
  
  // Generate curve points
  for (let i = 0; i <= tubeSegments; i++) {
    const phi = (i / tubeSegments) * Math.PI * 2;
    const r = majorRadius + minorRadius * Math.cos(qParam * phi);
    const x = r * Math.cos(pParam * phi);
    const y = r * Math.sin(pParam * phi);
    const z = minorRadius * Math.sin(qParam * phi);
    knotPoints.push({ x, y, z });
  }
  
  const triangles: Triangle[] = [];
  const tubeVertices: Vertex[][] = []; // grid tubeSegments x radialSegments
  
  // Generate Frenet-Serret-like frame for each curve point
  for (let i = 0; i < tubeSegments; i++) {
    const curr = knotPoints[i];
    const next = knotPoints[i + 1];
    
    // Tangent
    const tx = next.x - curr.x;
    const ty = next.y - curr.y;
    const tz = next.z - curr.z;
    const tLen = Math.sqrt(tx * tx + ty * ty + tz * tz);
    const T = { x: tx / tLen, y: ty / tLen, z: tz / tLen };
    
    // Normal (use curve direction relative to origin for a stable coordinate system)
    const nx = curr.x;
    const ny = curr.y;
    const nz = 0; // lock to horizontal plane for safety
    const nLen = Math.sqrt(nx * nx + ny * ny + nz * nz);
    const N = { x: nx / nLen, y: ny / nLen, z: nz / nLen };
    
    // Binormal (Cross product T x N)
    const B = {
      x: T.y * N.z - T.z * N.y,
      y: T.z * N.x - T.x * N.z,
      z: T.x * N.y - T.y * N.x
    };
    const bLen = Math.sqrt(B.x * B.x + B.y * B.y + B.z * B.z);
    B.x /= bLen;
    B.y /= bLen;
    B.z /= bLen;
    
    // Re-adjust normal N to make sure it's strictly perpendicular to T and B
    N.x = B.y * T.z - B.z * T.y;
    N.y = B.z * T.x - B.x * T.z;
    N.z = B.x * T.y - B.y * T.x;
    
    // Generate rings around the curve point
    const ring: Vertex[] = [];
    const radius = 3.5; // thickness of knot tube
    for (let rIdx = 0; rIdx < radialSegments; rIdx++) {
      const theta = (rIdx / radialSegments) * Math.PI * 2;
      const cosT = Math.cos(theta);
      const sinT = Math.sin(theta);
      
      ring.push({
        x: curr.x + radius * (cosT * N.x + sinT * B.x),
        y: curr.y + radius * (cosT * N.y + sinT * B.y),
        z: curr.z + radius * (cosT * N.z + sinT * B.z)
      });
    }
    tubeVertices.push(ring);
  }
  
  // Close the tube loop by adding the 0th ring as the last ring
  tubeVertices.push(tubeVertices[0]);
  
  // Construct faces
  for (let i = 0; i < tubeSegments; i++) {
    const ring1 = tubeVertices[i];
    const ring2 = tubeVertices[i + 1];
    
    for (let r = 0; r < radialSegments; r++) {
      const nextR = (r + 1) % radialSegments;
      
      const v00 = ring1[r];
      const v10 = ring2[r];
      const v01 = ring1[nextR];
      const v11 = ring2[nextR];
      
      // Triangle 1: (v00, v10, v11)
      {
        const p1: [number, number, number] = [v00.x, v00.y, v00.z];
        const p2: [number, number, number] = [v10.x, v10.y, v10.z];
        const p3: [number, number, number] = [v11.x, v11.y, v11.z];
        triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
      }
      
      // Triangle 2: (v00, v11, v01)
      {
        const p1: [number, number, number] = [v00.x, v00.y, v00.z];
        const p2: [number, number, number] = [v11.x, v11.y, v11.z];
        const p3: [number, number, number] = [v01.x, v01.y, v01.z];
        triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
      }
    }
  }
  
  return serializeBinarySTL(triangles, "TorusKnot_2x3");
}
